// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmEZ0Kfh_XySt0HYdsk4nfQ_QLYPSTKoE',
    appId: '1:236706773512:web:b429963cdf6eb538982fbd',
    messagingSenderId: '236706773512',
    projectId: 'exam-permit',
    authDomain: 'exam-permit.firebaseapp.com',
    databaseURL: 'https://exam-permit-default-rtdb.firebaseio.com',
    storageBucket: 'exam-permit.firebasestorage.app',
    measurementId: 'G-KRRT6K6C97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCiNQs0bFYSV-SaONACdJ1Yb9rPl7y2JUs',
    appId: '1:236706773512:android:806a52a53418cc76982fbd',
    messagingSenderId: '236706773512',
    projectId: 'exam-permit',
    databaseURL: 'https://exam-permit-default-rtdb.firebaseio.com',
    storageBucket: 'exam-permit.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBf_itnfn7gR7BCICxcUDgDK_xPNaFdTKA',
    appId: '1:236706773512:ios:510ca55e0941e65e982fbd',
    messagingSenderId: '236706773512',
    projectId: 'exam-permit',
    databaseURL: 'https://exam-permit-default-rtdb.firebaseio.com',
    storageBucket: 'exam-permit.firebasestorage.app',
    iosBundleId: 'com.example.specialExamPermit',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBf_itnfn7gR7BCICxcUDgDK_xPNaFdTKA',
    appId: '1:236706773512:ios:510ca55e0941e65e982fbd',
    messagingSenderId: '236706773512',
    projectId: 'exam-permit',
    databaseURL: 'https://exam-permit-default-rtdb.firebaseio.com',
    storageBucket: 'exam-permit.firebasestorage.app',
    iosBundleId: 'com.example.specialExamPermit',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmEZ0Kfh_XySt0HYdsk4nfQ_QLYPSTKoE',
    appId: '1:236706773512:web:353b568b86c6c3e0982fbd',
    messagingSenderId: '236706773512',
    projectId: 'exam-permit',
    authDomain: 'exam-permit.firebaseapp.com',
    databaseURL: 'https://exam-permit-default-rtdb.firebaseio.com',
    storageBucket: 'exam-permit.firebasestorage.app',
    measurementId: 'G-H9E94HDGCL',
  );
}
